'use strict';
/**
 * gen_format_data.js — writes web-app/format-data.js from spec/cimbar-v2.json
 * so the browser (which cannot require() JSON) sees the same constants.
 * Usage: node tools/gen_format_data.js
 */
const fs = require('fs');
const path = require('path');

const specPath = path.join(__dirname, '..', '..', 'spec', 'cimbar-v2.json');
const outPath = path.join(__dirname, '..', 'format-data.js');

function render(specText) {
  const spec = JSON.parse(specText); // validates
  return '/* GENERATED by web-app/tools/gen_format_data.js from spec/cimbar-v2.json — do not edit */\n' +
    "'use strict';\n" +
    'window.CIMBAR_SPEC = ' + JSON.stringify(spec) + ';\n';
}

if (require.main === module) {
  fs.writeFileSync(outPath, render(fs.readFileSync(specPath, 'utf8')));
  console.log('wrote ' + outPath);
}

module.exports = { render, specPath, outPath };
